#!/usr/bin/env python3
"""Generate example documentation wrappers from colocated example docs."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Dict, List, Set

STAGED_EXAMPLES_DIR = "_example_assets"
STAGED_EXAMPLE_INCLUDES_DIR = "_example_includes"


def repo_root_from_script() -> Path:
    return Path(__file__).resolve().parents[3]


def read_json(path: Path) -> object:
    return json.loads(path.read_text(encoding="utf-8"))


def ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def relative_path(from_dir: Path, target: Path) -> str:
    return Path(os.path.relpath(str(target), str(from_dir))).as_posix()


def render_include(page_dir: Path, readme_path: Path) -> str:
    link = relative_path(page_dir, readme_path)
    return "\n".join([
        "```{{include}} {0}".format(link),
        ":relative-images:",
        "```",
    ])

def load_string_list(entry: Dict[str, object], key: str) -> List[str]:
    value = entry.get(key, [])
    if not isinstance(value, list):
        raise ValueError("{0} must be an array".format(key))
    items: List[str] = []
    for raw_item in value:
        item = str(raw_item).strip()
        if item:
            items.append(item)
    return items


def tracked_meta_files(entry: Dict[str, object]) -> Set[str]:
    files: Set[str] = {"README.md", "meta.json"}
    for key in ("inputs", "outputs", "doc_images"):
        files.update(load_string_list(entry, key))

    preview = str(entry.get("preview", "")).strip()
    if preview:
        files.add(preview)
    return files


def load_meta_examples(examples_dir: Path) -> List[Dict[str, object]]:
    entries: List[Dict[str, object]] = []
    for meta_path in sorted(examples_dir.glob("*/meta.json")):
        raw = read_json(meta_path)
        if not isinstance(raw, dict):
            raise ValueError("{0} must contain an object".format(meta_path))

        entry = dict(raw)
        entry["name"] = meta_path.parent.name
        entry["example_dir"] = meta_path.parent
        entry["meta_path"] = meta_path
        entry["readme_path"] = meta_path.parent / "README.md"
        entries.append(entry)

    entries.sort(key=lambda item: (int(item.get("order", 9999)), item["name"]))
    return entries


def validate_entry(
    entry: Dict[str, object],
) -> None:
    for key in ("slug", "label", "title", "card_title"):
        value = str(entry.get(key, "")).strip()
        if not value:
            raise ValueError(
                "Missing {0} in {1}".format(key, entry["meta_path"])
            )
    for key in ("inputs", "outputs", "doc_images"):
        load_string_list(entry, key)


def render_page(
    page_path: Path,
    meta_entry: Dict[str, object],
) -> str:
    label = str(meta_entry["label"])
    title = str(meta_entry["title"])
    readme_path = (
        page_path.parents[2] /
        STAGED_EXAMPLE_INCLUDES_DIR /
        "{0}.md".format(meta_entry["name"])
    )

    lines: List[str] = [
        "<!-- Generated by doc/user/tools/generate_examples_docs.py -->",
        "",
        "({0})=".format(label),
        "# {0}".format(title),
    ]

    if readme_path.exists():
        lines.extend(["", render_include(page_path.parent, readme_path)])

    lines.append("")
    return "\n".join(lines)


def render_index(
    index_path: Path,
    entries: List[Dict[str, object]],
) -> str:
    lines = [
        "<!-- Generated by doc/user/tools/generate_examples_docs.py -->",
        "",
        "# Examples",
        "",
        "```{toctree}",
        ":hidden:",
        "",
    ]

    for entry in entries:
        lines.append(str(entry["slug"]))

    lines.extend([
        "```",
        "",
        "::::{grid} 1 2 3 3",
        ":gutter: 3",
        "",
    ])

    for entry in entries:
        preview_path = index_path.parents[2] / STAGED_EXAMPLES_DIR / str(
            entry["name"]
        ) / str(entry["preview"])
        lines.extend([
            ":::{grid-item-card}",
            ":link: {0}".format(entry["label"]),
            ":link-type: ref",
            ":img-top: {0}".format(
                relative_path(index_path.parent, preview_path)
            ),
            "",
            "+++",
            str(entry["card_title"]),
            ":::",
            "",
            "",
        ])

    lines.append("::::")
    lines.append("")
    return "\n".join(lines)


def write_text(path: Path, text: str) -> None:
    ensure_parent(path)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate example page wrappers from share/examples."
    )
    parser.add_argument(
        "--output-dir",
        help="write generated files to a custom directory",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="render pages and print target paths without writing files",
    )
    args = parser.parse_args()

    repo_root = repo_root_from_script()
    examples_dir = repo_root / "share" / "examples"
    default_output_dir = (
        repo_root / "doc" / "user" / "source" / "contents" / "examples"
    )
    output_dir = Path(args.output_dir) if args.output_dir else default_output_dir

    entries = load_meta_examples(examples_dir)

    for entry in entries:
        validate_entry(entry)
        page_path = output_dir / "{0}.md".format(entry["slug"])
        content = render_page(page_path, entry)
        if args.dry_run:
            print("OK  {0} ({1} chars)".format(page_path, len(content)))
        else:
            write_text(page_path, content)

    index_path = output_dir / "index.md"
    index_content = render_index(index_path, entries)
    if args.dry_run:
        print("OK  {0} ({1} chars)".format(index_path, len(index_content)))
    else:
        write_text(index_path, index_content)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
