#!/bin/bash
C_COMPILER=gcc
CXX_COMPILER=g++
LIB_SEARCH_DIR="../..:/usr/lib64"

mkdir build_gui_linux_64
cd build_gui_linux_64
cmake -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_PREFIX_PATH=$LIB_SEARCH_DIR -DCMAKE_BUILD_TYPE=Release -DDEFAULT=0 -DENABLE_ANN=1 -DENABLE_BUILD_SHARED=1 -DENABLE_CXX11=1 -DENABLE_FLTK=1 -DENABLE_MESH=1 -DENABLE_OCC=0 -DENABLE_ONELAB=1 -DENABLE_PARSER=1 -DENABLE_PLUGINS=1 -DENABLE_POST=1 -DCMAKE_INSTALL_PREFIX="../.." ..
