# -*- coding: utf-8 -*-
import os
import re
import shutil
import json
from pathlib import Path
#
# v4d documentation build configuration file, created by
# sphinx-quickstart on Tue May 30 13:54:05 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project configuration ------------------------------------------------

# General information about the project.
project = u'PreVABS'
# copyright = u'2017, xl&st'
author = u'Su Tian, Haodong Du, Xin Liu and Wenbin Yu'


def loadPrevabsVersion():
    repo_root = Path(__file__).resolve().parents[3]
    cmake_path = repo_root / 'CMakeLists.txt'
    cmake_content = cmake_path.read_text(encoding='utf-8')

    version_match = re.search(
        r'set\s*\(\s*PREVABS_VERSION\s+"([^"]+)"\s*\)',
        cmake_content
    )
    if version_match:
        return version_match.group(1)

    components = {}
    for name in ('MAJOR', 'MINOR', 'PATCH'):
        component_match = re.search(
            r'set\s*\(\s*PREVABS_VERSION_{0}\s+(\d+)\s*\)'.format(name),
            cmake_content
        )
        if not component_match:
            raise RuntimeError(
                'Could not find PREVABS_VERSION_{0} in {1}'.format(
                    name, cmake_path
                )
            )
        components[name] = component_match.group(1)

    return '{MAJOR}.{MINOR}.{PATCH}'.format(**components)


PREVABS_VERSION = loadPrevabsVersion()

STAGED_EXAMPLES_DIR = '_example_assets'
STAGED_EXAMPLE_INCLUDES_DIR = '_example_includes'


def isLocalAssetTarget(target):
    return (
        target and
        '://' not in target and
        not target.startswith('#') and
        not target.startswith('/')
    )


def readJson(path):
    return json.loads(path.read_text(encoding='utf-8'))


def loadStringList(entry, key):
    value = entry.get(key, [])
    if not isinstance(value, list):
        raise ValueError('{0} must be an array in {1}'.format(
            key,
            entry.get('name', '<unknown>')
        ))
    items = []
    for raw_item in value:
        item = str(raw_item).strip()
        if item:
            items.append(item)
    return items


def trackedMetaFiles(entry):
    files = set(['README.md', 'meta.json'])
    for key in ('inputs', 'outputs', 'doc_images'):
        files.update(loadStringList(entry, key))

    preview = str(entry.get('preview', '')).strip()
    if preview:
        files.add(preview)
    return files


def rewriteExampleReadme(content, example_name):
    asset_prefix = '../../{0}/{1}/'.format(
        STAGED_EXAMPLES_DIR,
        example_name,
    )

    def rewrite_figure(match):
        target = match.group(2).strip()
        if isLocalAssetTarget(target):
            target = asset_prefix + target
        return '{0}{1}'.format(match.group(1), target)

    def rewrite_link(match):
        label = match.group(1)
        target = match.group(2).strip()
        if isLocalAssetTarget(target):
            target = asset_prefix + target
        return '[{0}]({1})'.format(label, target)

    content = re.sub(
        r'^(```\{figure\}\s+)(\S+)\s*$',
        rewrite_figure,
        content,
        flags=re.MULTILINE
    )
    content = re.sub(
        r'\[([^\]]+)\]\(([^)]+)\)',
        rewrite_link,
        content
    )
    return content


def stageExampleAssets():
    repo_root = Path(__file__).resolve().parents[3]
    source_dir = Path(__file__).resolve().parent
    examples_src = repo_root / 'share' / 'examples'
    examples_dst = source_dir / STAGED_EXAMPLES_DIR
    includes_dst = source_dir / STAGED_EXAMPLE_INCLUDES_DIR

    if examples_dst.exists():
        shutil.rmtree(str(examples_dst))
    if includes_dst.exists():
        shutil.rmtree(str(includes_dst))
    examples_dst.mkdir(parents=True)
    includes_dst.mkdir(parents=True)

    for example_dir in sorted(examples_src.iterdir()):
        if not example_dir.is_dir():
            continue
        meta_src = example_dir / 'meta.json'
        if not meta_src.exists():
            continue

        meta = readJson(meta_src)
        if not isinstance(meta, dict):
            raise ValueError('{0} must contain an object'.format(meta_src))
        meta['name'] = example_dir.name

        staged_example_dir = examples_dst / example_dir.name
        staged_example_dir.mkdir(parents=True)
        for filename in sorted(trackedMetaFiles(meta)):
            src = example_dir / filename
            if not src.exists():
                raise FileNotFoundError(
                    'Tracked example file not found: {0}'.format(src)
                )
            shutil.copy2(str(src), str(staged_example_dir / filename))

        readme_src = example_dir / 'README.md'
        if readme_src.exists():
            rewritten = rewriteExampleReadme(
                readme_src.read_text(encoding='utf-8'),
                example_dir.name
            )
            (includes_dst / '{0}.md'.format(example_dir.name)).write_text(
                rewritten,
                encoding='utf-8',
                newline='\n'
            )


stageExampleAssets()

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = PREVABS_VERSION
# The full version, including alpha/beta/rc tags.
release = PREVABS_VERSION



# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.mathjax',
    'sphinx.ext.napoleon',
    'sphinx_design',
    # 'sphinx_gallery',
    'sphinx-prompt',
    'sphinx_copybutton',
    # 'sphinxcontrib.bibtex',
    'myst_parser',
]


def loadMystSubstitutions(filename):
    substitutions = {}
    path = os.path.join(os.path.dirname(__file__), filename)
    with open(path, 'r') as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if (not line or line.startswith('#') or
                    not line.startswith('|')):
                continue
            if '| Key ' in line or '| --- ' in line:
                continue
            parts = [part.strip() for part in line.split('|')[1:-1]]
            if len(parts) < 2:
                continue
            key = parts[0].strip('`')
            value = parts[1]
            substitutions[key] = value
    return substitutions

myst_enable_extensions = [
    "amsmath",
    "attrs_inline",
    "colon_fence",
    "deflist",
    "dollarmath",
    "fieldlist",
    "html_admonition",
    "html_image",
    "replacements",
    "smartquotes",
    "strikethrough",
    "substitution",
    "tasklist",
]

myst_substitutions = loadMystSubstitutions('myst_substitutions.md')

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# Allow both reStructuredText and MyST Markdown sources.
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

# The master toctree document.
# master_doc = 'index'
root_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = [
    '_build',
    'Thumbs.db',
    '.DS_Store',
    '_*.rst',
    '_example_assets',
    '_example_includes',
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

rst_prolog = '\n'.join([
".. include:: /replace.txt",
])

rst_epilog = """
"""


numfig = True
numfig_format = {
    'figure': 'Figure %s',
    'table': 'Table %s',
    'code-block': 'Listing %s',
    'section': 'Section'}


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
# html_theme = 'bizstyle'
# html_theme = 'classic'
# html_theme = 'nature'
# html_theme = 'sphinxdoc'
# html_theme = 'sphinx_rtd_theme'
# html_theme = 'sphinx_book_theme'
# html_theme = 'sphinx_material'
html_theme = 'pydata_sphinx_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'logo': {
        'text': 'PreVABS',
    },
    'show_nav_level': 2,
    # "path_to_docs": "doc/source",
    # 'use_edit_page_button': True,
    # "use_repository_button": True,
    # "use_issues_button": True,
    # 'collapse_navigation': True,
    'navigation_depth': 4,
    "announcement": "Documentation is under construction.",
}

html_show_copyright = False

# html_sidebars = {
#   '**': ['localtoc.html', 'globaltoc.html']
# }

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']



# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',

    'releasename': 'Version'
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (root_doc, 'PreVABSManual.tex', u"PreVABS User's Manual",
     author, 'manual'),
]


# -- Options for extensions ---------------------------------------------


myst_enable_extensions = [
    "colon_fence",
    "dollarmath",
    "amsmath"
]

