#pragma once

// Stage B of plan-20260514-clipper2-offset-backend.md.
//
// Pure-geometry layer: Clipper2 InflatePaths wrapper that translates
// a PreVABS yz-plane polyline into a Clipper2 PathD, runs the offset,
// and projects each output vertex back onto a base segment so the
// downstream reverse-matching bridge (Stage C) can build a
// BaseOffsetMap.
//
// **No PDCELVertex / BaseOffsetMap awareness.** This module is
// deliberately decoupled from the rest of PreVABS so the same
// `offsetWithClipper2` can be reused by the long-term end-state
// nested-offset orchestrator (see plan-20260515 §8) without rewrite.
// Callers convert their PDCELVertex sequence to SPoint2 in yz before
// calling, and consume `OffsetPolygon` afterwards.

#include "geo_types.hpp"

#include <vector>

namespace prevabs {
namespace geo {

/// One offset output vertex's relationship to the input base curve.
///
/// `base_seg`:
///   - in [0, N_seg)  → this output vertex projects onto input segment
///                      `base_seg`, with foot of perpendicular at
///                      parameter `base_u ∈ [0, 1]` on that segment.
///   - -1             → no input segment lies within `1.5 * |dist|`
///                      of this output vertex. Such a vertex was
///                      generated by Clipper2 at a miter / bevel
///                      join point and has no input correspondence.
///
/// The caller (Stage C reverse-matching bridge) uses these annotations
/// to fold the output back onto the legacy `BaseOffsetMap` staircase.
struct OffsetVertexSource {
  int    base_seg;
  double base_u;
};

/// One polygon in the offset result. Clipper2 may return multiple in
/// disconnected-branch scenarios (e.g. thin TE airfoils where the
/// inset pinches the contour into separate pieces).
struct OffsetPolygon {
  std::vector<SPoint2>            points;
  std::vector<OffsetVertexSource> sources;   // size == points.size()
  // is_closed = true   → closed offset polygon (closed-input branch).
  //                     `points` walks the perimeter; `points.front()`
  //                     and `points.back()` are distinct (no trailing
  //                     duplicate; closure is implicit).
  // is_closed = false  → one-sided open polyline filtered from the
  //                     Butt wrap (open-input branch). `points`
  //                     traverses from the P_0 side toward P_{N-1};
  //                     base_seg in `sources` is non-decreasing.
  bool                            is_closed;
};

/// One row of a reverse-matched base/offset correspondence, expressed
/// in SPoint2 coordinates (yz plane). This is the SPoint2-only output
/// of `planReverseMatch` — the PDCELVertex-aware wrapper
/// `buildBaseOffsetMapFromOffsetPolygons` (declared below) consumes it
/// and produces PDCELVertex* outputs.
///
/// Designed as the data carrier between Stage B (Clipper2 geometry)
/// and Stage D (offset() main-body replacement). Per plan-20260515
/// §8.4 the SPoint2 layer is forward-compatible with the future
/// end-state nested-offset orchestrator; the PDCELVertex wrapper is
/// the deletable adapter.
struct ReverseMatchPlan {
  /// Offset polygon vertices in walk order, in SPoint2 (yz).
  /// For a closed input, `offset_points[0]` is the rotated "anchor"
  /// (it does NOT carry a trailing duplicate — the PDCELVertex
  /// wrapper appends the dup pointer when materializing).
  std::vector<SPoint2> offset_points;

  /// Staircase base→offset correspondence — see
  /// include/geo_types.hpp:27 for the invariant. For a closed input
  /// the last entry is `(N_base_distinct, M_off_raw)` so the caller
  /// can wire the trailing duplicate cleanly.
  BaseOffsetMap        id_pairs;

  /// Contiguous spans of base indices that have NO geometric
  /// correspondence on the offset side (Clipper2 "ate" them because
  /// the local half-thickness was insufficient). Each
  /// (dropped_base_ranges_lo[k], dropped_base_ranges_hi[k]) is an
  /// inclusive [lo..hi] range. These base indices still appear in
  /// `id_pairs` (forward-filled to the closest offset index left of
  /// the gap) so downstream PSegment::build stays in-bounds — but
  /// callers should log them as "skin dropped over base indices ..."
  /// per plan §5.4.
  std::vector<int>     dropped_base_ranges_lo;
  std::vector<int>     dropped_base_ranges_hi;

  /// True when offset_points should be treated as a closed loop
  /// (caller appends a trailing-duplicate vertex pointer / pad point).
  bool                 closed = false;

  /// True iff the plan is non-empty and passes
  /// validateBaseOffsetMap. False when Clipper2 produced no
  /// polygons, or the inputs were degenerate.
  bool                 ok = false;

  /// Stage F multi-branch diagnostics: |signed area| of every
  /// disconnected polygon Clipper2 returned (ordered largest-first).
  /// `primary_polygon_area` is the area of the polygon that was kept
  /// as the staircase source; the remaining entries in
  /// `dropped_polygon_areas` are the silently discarded pieces. Both
  /// empty when Clipper2 returned a single connected polygon.
  double               primary_polygon_area = 0.0;
  std::vector<double>  dropped_polygon_areas;
};

/// Pure-logic reverse-match bridge. Operates entirely on SPoint2 +
/// index arithmetic; **no PDCELVertex** so it is unit-testable
/// outside the PreVABS DCEL ecosystem and reusable by the future
/// end-state nested-offset orchestrator (plan-20260515 §8.4).
///
/// @param base            Distinct base vertices in yz (caller MUST
///                        drop any trailing duplicate before calling).
/// @param base_is_closed  Whether the base implicitly closes from
///                        back to front.
/// @param side            +1 outward, -1 inward (diagnostic; geometry
///                        is already encoded in `polygons`).
/// @param dist            Magnitude of the offset distance.
/// @param polygons        Output of `offsetWithClipper2`. The
///                        function picks the "primary" polygon by:
///                          1. largest |signed area|; then if multiple
///                             candidates are within 5% of the best
///                             area,
///                          2. centroid closest to the base bounding-
///                             box centroid (Stage F tie-break;
///                             plan-20260514 §5.1 priority 2).
///                        Smaller pieces (if any) are dropped; their
///                        areas land in
///                        `ReverseMatchPlan::dropped_polygon_areas`
///                        so the caller can emit a detailed warning.
///
/// Returns a `ReverseMatchPlan` with `ok=false` when polygons is empty
/// or the staircase invariant cannot be restored (the caller MUST
/// check `ok` before using the plan).
ReverseMatchPlan planReverseMatch(
    const std::vector<SPoint2>&        base,
    bool                               base_is_closed,
    int                                side,
    double                             dist,
    const std::vector<OffsetPolygon>&  polygons);

/// Pure-geometry Clipper2 offset wrapper.
///
/// @param base            Input polyline in the yz plane.
///                        For closed inputs, the caller may omit the
///                        trailing duplicate vertex; if it is present
///                        the wrapper drops it defensively.
/// @param base_is_closed  true  → EndType::Polygon (implicit closing
///                                 edge from back to front; output is
///                                 a closed offset polygon).
///                        false → EndType::Butt (open-ended; output is
///                                 a one-sided OPEN polyline filtered
///                                 from the Butt-wrap by `side`).
/// @param side            +1 = left  of base (sign(t × d) > 0,
///                              CCW outward for a closed CCW input)
///                        -1 = right of base (sign(t × d) < 0,
///                              CCW inward  for a closed CCW input)
///                        Honored for BOTH closed and open inputs.
///                        For open inputs, the Butt wrap is filtered
///                        post-Clipper2 so each output is a one-sided
///                        open polyline (`is_closed = false`).
/// @param dist            Magnitude of offset distance, > 0.
///
/// Returns zero or more `OffsetPolygon` instances:
///   - closed input → one polygon per Clipper2 path (`is_closed=true`)
///   - open input   → one OPEN polyline per filtered side-run
///                    (`is_closed=false`). Well-formed inputs produce
///                    exactly one run with N or N+1 points (one per
///                    base vertex plus one Butt-cap point at each end).
/// Empty result indicates Clipper2 ate the input completely (local
/// half-thickness < dist) or all wrap vertices landed on the opposite
/// side from the requested one.
///
/// Implementation choices (locked in by A0 evidence; see
/// local/issue-20260515-clipper2-airfoil-a0.md):
///   - JoinType::Miter, miter_limit = 2.0
///   - precision = 8 (the Clipper2 1.4.0 hard ceiling)
std::vector<OffsetPolygon> offsetWithClipper2(
    const std::vector<SPoint2>& base,
    bool                        base_is_closed,
    int                         side,
    double                      dist);

}  // namespace geo
}  // namespace prevabs


// Forward declaration so callers and tests that do not need the full
// PDCEL header chain can still include this header.
class PDCELVertex;

namespace prevabs {
namespace geo {

/// PDCELVertex-aware reverse-match result. Stage D wires this into
/// the legacy `offset()` signature in src/geo/offset.cpp.
struct ReverseMatchResult {
  /// Newly allocated PDCELVertex* (caller takes ownership).
  /// Convention:
  ///   - closed input  → `offset_vertices.front() == .back()` (same
  ///                     pointer), matching the PreVABS Baseline
  ///                     trailing-duplicate convention. Size =
  ///                     M_off_raw + 1.
  ///   - open   input  → `offset_vertices.front()` and `.back()` are
  ///                     distinct pointers, end-to-end 1:1 aligned
  ///                     with `base.front()` and `base.back()`.
  ///                     Size = M_off_raw.
  std::vector<PDCELVertex*> offset_vertices;
  /// Staircase per geo_types.hpp:27.
  ///   - closed → last entry is `(N_distinct, M_off_raw)` wrap pair.
  ///   - open   → last entry is `(N_distinct - 1, M_off_raw - 1)`,
  ///              no wrap pair.
  BaseOffsetMap             id_pairs;
  std::vector<int>          dropped_base_ranges_lo;
  std::vector<int>          dropped_base_ranges_hi;
  bool                      ok = false;
};

/// Stage C adapter (per plan-20260514 §5). Thin wrapper around
/// `planReverseMatch` that:
///   - extracts SPoint2 from PDCELVertex* (dropping the trailing
///     duplicate vertex if the caller passes a closed Baseline with
///     `base.front() == base.back()`; for open inputs the input
///     vector is consumed unchanged).
///   - calls `planReverseMatch`,
///   - allocates new PDCELVertex objects for each offset point.
///     For closed inputs, also appends the trailing-duplicate pointer
///     so `offset_vertices.front() == .back()`. Open inputs return
///     end-to-end distinct pointers with size == plan.offset_points
///     size.
///
/// Per plan-20260515 §8.4 this adapter is the planned deletion site
/// when the end-state nested-offset orchestrator replaces
/// `BaseOffsetMap`.
ReverseMatchResult buildBaseOffsetMapFromOffsetPolygons(
    const std::vector<PDCELVertex*>&   base,
    bool                               base_is_closed,
    int                                side,
    double                             dist,
    const std::vector<OffsetPolygon>&  polygons);

}  // namespace geo
}  // namespace prevabs
