#pragma once

// Stage B of plan-20260514-clipper2-offset-backend.md.
//
// Pure-geometry layer: Clipper2 InflatePaths wrapper that translates
// a PreVABS yz-plane polyline into a Clipper2 PathD, runs the offset,
// and projects each output vertex back onto a base segment so the
// downstream reverse-matching bridge (Stage C) can build a
// BaseOffsetMap.
//
// **No PDCELVertex / BaseOffsetMap awareness.** This module is
// deliberately decoupled from the rest of PreVABS so the same
// `offsetWithClipper2` can be reused by the long-term end-state
// nested-offset orchestrator (see plan-20260515 §8) without rewrite.
// Callers convert their PDCELVertex sequence to SPoint2 in yz before
// calling, and consume `OffsetPolygon` afterwards.

#include "geo_types.hpp"

#include <vector>

namespace prevabs {
namespace geo {

/// One offset output vertex's relationship to the input base curve.
///
/// `base_seg`:
///   - in [0, N_seg)  → this output vertex projects onto input segment
///                      `base_seg`, with foot of perpendicular at
///                      parameter `base_u ∈ [0, 1]` on that segment.
///   - -1             → no input segment lies within `1.5 * |dist|`
///                      of this output vertex. Such a vertex was
///                      generated by Clipper2 at a miter / bevel
///                      join point and has no input correspondence.
///
/// The caller (Stage C reverse-matching bridge) uses these annotations
/// to fold the output back onto the legacy `BaseOffsetMap` staircase.
struct OffsetVertexSource {
  int    base_seg;
  double base_u;
};

/// One polygon in the offset result. Clipper2 may return multiple in
/// disconnected-branch scenarios (e.g. thin TE airfoils where the
/// inset pinches the contour into separate pieces).
struct OffsetPolygon {
  std::vector<SPoint2>            points;
  std::vector<OffsetVertexSource> sources;   // size == points.size()
  // Per-vertex origin tag (size == points.size()).
  //   false → vertex came straight out of Clipper2 (raw corner / bevel /
  //           Butt-cap point). For closed inputs every vertex is raw.
  //   true  → vertex was synthesized by `extractOpenRuns`'s base-vertex
  //           resample step (foot-of-perpendicular projection of a base
  //           vertex onto the raw run polyline). Only ever true on the
  //           open-input branch.
  std::vector<bool>               resampled;
  // Debug-only snapshot of the raw Clipper2 run polyline taken
  // immediately before `extractOpenRuns`'s foot-of-perpendicular
  // resample step replaced every vertex in this run. Empty when the
  // run never went through the resample branch (e.g. M >= N, or
  // closed-input branch). The positions are otherwise unrecoverable
  // because the resample commit overwrites `points` and tags every
  // slot `resampled=true`. See `extractOpenRuns` in
  // src/geo/offset_clipper2.cpp.
  std::vector<SPoint2>            pre_resample_points;
  // is_closed = true   → closed offset polygon (closed-input branch).
  //                     `points` walks the perimeter; `points.front()`
  //                     and `points.back()` are distinct (no trailing
  //                     duplicate; closure is implicit).
  // is_closed = false  → one-sided open polyline filtered from the
  //                     Butt wrap (open-input branch). `points`
  //                     traverses from the P_0 side toward P_{N-1};
  //                     base_seg in `sources` is non-decreasing.
  bool                            is_closed;
};

/// One row of a reverse-matched base/offset correspondence, expressed
/// in SPoint2 coordinates (yz plane). This is the SPoint2-only output
/// of `planReverseMatch` — the PDCELVertex-aware wrapper
/// `buildBaseOffsetMapFromOffsetPolygons` (declared below) consumes it
/// and produces PDCELVertex* outputs.
///
/// Designed as the data carrier between Stage B (Clipper2 geometry)
/// and Stage D (offset() main-body replacement). Per plan-20260515
/// §8.4 the SPoint2 layer is forward-compatible with the future
/// end-state nested-offset orchestrator; the PDCELVertex wrapper is
/// the deletable adapter.
struct ReverseMatchPlan {
  /// Offset polygon vertices in walk order, in SPoint2 (yz).
  /// For a closed input, `offset_points[0]` is the rotated "anchor"
  /// (it does NOT carry a trailing duplicate — the PDCELVertex
  /// wrapper appends the dup pointer when materializing).
  std::vector<SPoint2> offset_points;

  /// Per-vertex origin tag, parallel to `offset_points` (see
  /// `OffsetPolygon::resampled` for the convention). Carried through
  /// the bridge so the PDCELVertex adapter can hand it to debug
  /// visualizers.
  std::vector<bool>    offset_resampled;

  /// Debug-only snapshot of the primary polygon's raw Clipper2 vertices
  /// captured immediately before the open-path resample step replaced
  /// them. Empty when the primary run never went through resample.
  /// No rotation is applied — order is the run-extractor's native walk
  /// (it is used only as an unordered scatter overlay).
  std::vector<SPoint2> pre_resample_raw_points;

  /// Staircase base→offset correspondence — see
  /// include/geo_types.hpp:27 for the invariant. For a closed input
  /// the last entry is `(N_base_distinct, M_off_raw)` so the caller
  /// can wire the trailing duplicate cleanly.
  BaseOffsetMap        id_pairs;

  /// Contiguous spans of base indices that have NO geometric
  /// correspondence on the offset side (Clipper2 "ate" them because
  /// the local half-thickness was insufficient). Each
  /// (dropped_base_ranges_lo[k], dropped_base_ranges_hi[k]) is an
  /// inclusive [lo..hi] range. These base indices still appear in
  /// `id_pairs` (forward-filled to the closest offset index left of
  /// the gap) so downstream PSegment::build stays in-bounds — but
  /// callers should log them as "skin dropped over base indices ..."
  /// per plan §5.4.
  std::vector<int>     dropped_base_ranges_lo;
  std::vector<int>     dropped_base_ranges_hi;

  /// True when offset_points should be treated as a closed loop
  /// (caller appends a trailing-duplicate vertex pointer / pad point).
  bool                 closed = false;

  /// True iff the plan is non-empty and passes
  /// validateBaseOffsetMap. False when Clipper2 produced no
  /// polygons, or the inputs were degenerate.
  bool                 ok = false;

  /// Stage F multi-branch diagnostics: |signed area| of every
  /// disconnected polygon Clipper2 returned (ordered largest-first).
  /// `primary_polygon_area` is the area of the polygon that was kept
  /// as the staircase source; the remaining entries in
  /// `dropped_polygon_areas` are the silently discarded pieces. Both
  /// empty when Clipper2 returned a single connected polygon.
  double               primary_polygon_area = 0.0;
  std::vector<double>  dropped_polygon_areas;
};

/// Pure-logic reverse-match bridge. Operates entirely on SPoint2 +
/// index arithmetic; **no PDCELVertex** so it is unit-testable
/// outside the PreVABS DCEL ecosystem and reusable by the future
/// end-state nested-offset orchestrator (plan-20260515 §8.4).
///
/// @param base            Distinct base vertices in yz (caller MUST
///                        drop any trailing duplicate before calling).
/// @param base_is_closed  Whether the base implicitly closes from
///                        back to front.
/// @param side            +1 outward, -1 inward (diagnostic; geometry
///                        is already encoded in `polygons`).
/// @param dist            Magnitude of the offset distance.
/// @param polygons        Output of `offsetWithClipper2`. The
///                        function picks the "primary" polygon by:
///                          1. largest |signed area|; then if multiple
///                             candidates are within 5% of the best
///                             area,
///                          2. centroid closest to the base bounding-
///                             box centroid (Stage F tie-break;
///                             plan-20260514 §5.1 priority 2).
///                        Smaller pieces (if any) are dropped; their
///                        areas land in
///                        `ReverseMatchPlan::dropped_polygon_areas`
///                        so the caller can emit a detailed warning.
///
/// Returns a `ReverseMatchPlan` with `ok=false` when polygons is empty
/// or the staircase invariant cannot be restored (the caller MUST
/// check `ok` before using the plan).
ReverseMatchPlan planReverseMatch(
    const std::vector<SPoint2>&        base,
    bool                               base_is_closed,
    int                                side,
    double                             dist,
    const std::vector<OffsetPolygon>&  polygons);

/// Collapse degenerate "vertical" staircase steps whose two offset
/// endpoints are geometrically coincident (a zero-length offset edge
/// Clipper2 can emit at a sharp concave cusp). Drops the duplicate
/// offset vertex and re-indexes `id_pairs` / `offset_points` /
/// `offset_resampled` in place, restoring a 1:1 base↔offset count so the
/// layered-offset builder does not fall back to the legacy path (whose
/// zero-width area corrupts the DCEL → bad_alloc). OPEN inputs only;
/// closed plans (which wrap modularly) are left untouched.
void collapseCoincidentOffsetSteps(ReverseMatchPlan& m);

/// Alternative reverse-match using a **point-to-point nearest-vertex**
/// criterion instead of the segment-projection + segment-midpoint
/// rounding used by `planReverseMatch` / `attributeOne`.
///
/// Motivation: at sharp folds (e.g. airfoil thin TE), `attributeSource`
/// projects an offset vertex onto a segment and `attributeOne` rounds
/// to whichever segment endpoint has `u > 0.5`. The midpoint threshold
/// is discontinuous, so a small perturbation at a high-curvature corner
/// can flip the assignment to the wrong base end. Point-to-point
/// nearest doesn't have this midpoint cliff.
///
/// Operates on the **pre-resample** raw Clipper2 vertex sequence when
/// available (i.e. `OffsetPolygon::pre_resample_points` non-empty),
/// otherwise falls back to `OffsetPolygon::points`. Bypasses the
/// `extractOpenRuns` base-vertex resample step entirely — the staircase
/// stair-step handles M != N natively.
///
/// Algorithm sketch:
///   1. Pick the primary polygon (same as planReverseMatch).
///   2. Build a per-offset "valid" mask via foot-distance to base
///      polyline; discard offsets > 1.5 * |dist| from the base (the
///      Clipper2 join-point criterion, identical to attributeSource).
///   3. Seed the walk at `j_seed = argmin_m |base[0] - off[m]|`.
///      For closed inputs, rotate the offset sequence so `off[0]`
///      becomes the seed (cyclic alignment with `base[0]`).
///   4. Forward pass: for each base[i], walk j forward from the
///      previous pairing until point-to-point distance starts
///      increasing; pair with the j_min.
///   5. Reverse pass: for each offset slot skipped between consecutive
///      forward-pass pairings, assign it to whichever of {i-1, i} is
///      geometrically nearer. Once switched from i-1 to i, stay at i.
///   6. Tail / pre-seed fill (open only): pre-seed offsets pair with
///      base[0], post-tail offsets pair with base[N-1].
///   7. Reuse `buildIdPairs` + `anchorAtZero` + `staircaseValid` for
///      the index-domain housekeeping (drop ranges, wrap pair, etc.).
///
/// Same signature as `planReverseMatch` for drop-in A/B comparison.
/// `planReverseMatch` is unchanged; callers must opt in to this
/// variant explicitly.
ReverseMatchPlan planReverseMatchByNearest(
    const std::vector<SPoint2>&        base,
    bool                               base_is_closed,
    int                                side,
    double                             dist,
    const std::vector<OffsetPolygon>&  polygons);

/// Cost weights for `planReverseMatchByDP` (min-sum dynamic programming).
///
/// Cost of pairing base[i] with offset[j] is:
///
///   c(i,j) = wd · |a-b|² / dist²
///          + wu · (u_i - v_j)²
///          + wt · (1 - |t_A_i · t_B_j|)
///          + wn · (r_ij · t_A_i)² / (|r_ij|² + eps)
///
/// where (u_i, v_j) are normalized cumulative arclengths on base/offset,
/// (t_A_i, t_B_j) are unit tangents, and r_ij = offset[j] - base[i].
/// Transition penalty `gap` is added on (i+1, j) and (i, j+1) steps
/// (diag transition (i+1, j+1) is free beyond the cell cost).
///
/// Defaults are the Phase A prototype values
/// (issue-20260522-dp-matcher-phase-a.md §2.2). Override only when
/// tuning a specific failure case in Phase D.
struct DPCostWeights {
  double wd  = 1.0;
  double wu  = 0.2;
  double wt  = 0.1;
  double wn  = 0.5;
  double gap = 0.05;
  double eps = 1e-9;
};

/// Pairing-algorithm selector consumed by `rebuildBaseOffsetMapFromGeometry`
/// and the production dispatcher in `buildBaseOffsetMapFromOffsetPolygons`.
/// The three variants are kept side-by-side during Phase D tuning; one of
/// them becomes the default in Phase E.
///
///   SegmentProjection  legacy planReverseMatch (foot-of-perpendicular
///                      + segment-midpoint round, see `attributeOne`).
///   Nearest            planReverseMatchByNearest (point-to-point
///                      greedy forward walk; current default).
///   DP                 planReverseMatchByDP (min-sum dynamic
///                      programming with four-term geometric cost).
enum class PairingAlgo {
  SegmentProjection,
  Nearest,
  DP,
};

/// Single source of truth for the pairing-algo selector env-var.
/// Reads `PREVABS_PAIRING_ALGO` once per process and caches the result.
///
///   segment | seg | segment_projection  → SegmentProjection (default)
///   nearest                              → Nearest
///   dp                                   → DP
///
/// Value matching is case-insensitive. Unset / empty / unknown values
/// return `SegmentProjection` — the de-facto pre-Phase-C production
/// default that the integration-test Phase 4 baseline (29 pass / 5
/// fail) was measured under. Phase E may flip the default once Phase D
/// validates a different algorithm on the failing set.
PairingAlgo readPairingAlgoEnv();

/// Constrained monotone curve matcher via min-sum dynamic programming.
///
/// Algorithm:
///   1. Pick the primary polygon (same rule as planReverseMatch /
///      planReverseMatchByNearest).
///   2. Use the raw pre-resample vertex sequence when available,
///      otherwise the post-resample `points`.
///   3. For closed inputs, seed at `j_seed = argmin_m |base[0] - off[m]|`
///      and rotate the offset sequence so off[0] == off[j_seed]. Open
///      inputs walk the source sequence directly.
///   4. Fill DP table D[N][M] (min-sum) with three transitions
///      ({i-1,j-1}, {i-1,j}+gap, {i,j-1}+gap) and the four-term cost
///      (see `DPCostWeights`). Boundary rows/cols use accumulated cost
///      + per-step gap.
///   5. Backtrack from (N-1, M-1) to (0, 0). For each offset slot m
///      take the largest base index seen at j=m → walked[m].
///   6. Hand walked to the shared `buildIdPairs` / `anchorAtZero` /
///      `staircaseValid` helpers — index-gap drops fall out for free.
///   7. Geometric refinement: any pair (bi, oj) with
///      |base[bi] - off[oj]| > 1.5·dist is additionally marked
///      dropped (catches the diagonal-borderline case from
///      issue-20260522-dp-matcher-phase-a.md §3.1).
///
/// Same signature shape as `planReverseMatch` /
/// `planReverseMatchByNearest` so callers can A/B drop in a single
/// dispatch site. `weights == nullptr` uses the `DPCostWeights` defaults.
ReverseMatchPlan planReverseMatchByDP(
    const std::vector<SPoint2>&        base,
    bool                               base_is_closed,
    int                                side,
    double                             dist,
    const std::vector<OffsetPolygon>&  polygons,
    const DPCostWeights*               weights = nullptr);

/// Rebuild a `BaseOffsetMap` (and any derived dropped-base ranges)
/// purely from the **current geometry** of a base polyline and its
/// already-materialized offset polyline. Does NOT invoke Clipper2 —
/// the offset polyline is treated as ground truth, and the staircase
/// is reverse-engineered from the two polylines using the
/// nearest-point pairing rules of `planReverseMatchByNearest`.
///
/// Use case (plan-20260522 Phase 1): once `offset()` has populated
/// `_curve_offset` and `_base_offset_indices_pairs`, downstream stages
/// (join, build) may trim / mutate `_curve_base` and `_curve_offset`.
/// Rather than splicing the discrete `BaseOffsetMap` in lockstep, the
/// caller can drop the stored map and re-derive it from the post-trim
/// geometry just before consumers (`createIntermediateAreas`, etc.)
/// iterate the staircase.
///
/// @param base            Distinct base vertices in yz (drop trailing
///                        duplicate on closed inputs before calling).
/// @param offset          Offset polyline vertices in walk order.
///                        For closed inputs the caller may pass either
///                        a leading/trailing duplicate or not; this
///                        function drops a trailing duplicate
///                        defensively.
/// @param base_is_closed  Whether the base implicitly closes back to
///                        front.
/// @param side            +1 outward, -1 inward. Diagnostic only —
///                        geometry already encodes the side.
/// @param dist            Magnitude of the original offset distance.
///                        Used only for the 1.5·dist foot-of-
///                        perpendicular acceptance gate (mirrors
///                        `attributeSource`); the offset polyline
///                        itself is not regenerated.
/// @param algo            Pairing algorithm selector — must match the
///                        algorithm production `offset()` used when
///                        first populating `_base_offset_indices_pairs`
///                        (otherwise the derived staircase diverges
///                        by algorithm choice rather than geometry).
///                        Callers in segment-area rebuild should pass
///                        `readPairingAlgoEnv()`.
///
/// Returns a `ReverseMatchPlan` with `ok=true` and the same data
/// shape as `planReverseMatchByNearest`. `ok=false` indicates the
/// inputs were too short or the staircase invariant could not be
/// restored — the caller MUST check `ok` before using the plan.
ReverseMatchPlan rebuildBaseOffsetMapFromGeometry(
    const std::vector<SPoint2>&        base,
    const std::vector<SPoint2>&        offset,
    bool                               base_is_closed,
    int                                side,
    double                             dist,
    PairingAlgo                        algo = PairingAlgo::Nearest);

// ---------------------------------------------------------------------------
// Stage E pre-trim — plan-20260522-stage-e-pretrim.md.
//
// Removes a contiguous interior thin-cusp run from an OPEN base polyline
// before Clipper2 inset. Eliminates the M ≪ N degeneracy that causes
// downstream gmsh edge-recovery failures on airfoil thin-TE segments.
// Driver (offset.cpp) flow:
//   1. Build a thin_mask[] from `signedHalfThickness < α·|dist|` on the
//      original base polyline (interior INF treated as thin = cusp apex,
//      endpoints kept).
//   2. extractSingleInteriorRun(thin_mask, &run) — if exactly one
//      strictly-interior contiguous run, proceed; else fall back to the
//      untrimmed Clipper2 call.
//   3. buildTrimmedOpenPolyline(base_pts, run) — concat
//      base_pts[0..lo-1] + base_pts[hi+1..N-1]; the implicit
//      base_pts[lo-1]→base_pts[hi+1] segment in the trimmed polyline is
//      the "bridge" chord across the cusp tip.
//   4. offsetWithClipper2(trimmed, /*closed*/ false, side, dist).
//   5. remapBaseSegToOriginal(polygons, run) — fix-up
//      `OffsetVertexSource::base_seg` so attributions point at the
//      ORIGINAL base segments; offset vertices on the bridge segment
//      become `base_seg = -1`.
//   6. The driver injects `[run.lo, run.hi]` into the final
//      `dropped_base_ranges_lo/hi` so PSegment skips area construction
//      over the trimmed indices and a `PLOG(warning)` surfaces the
//      action to the user.
// ---------------------------------------------------------------------------

/// One contiguous interior thin-cusp range in original base indices.
/// Both endpoints inclusive. `lo > 0` and `hi < N - 1` strictly
/// (`extractSingleInteriorRun` enforces this).
struct ThinRun {
  int lo;
  int hi;
};

/// Find at most one strictly-interior contiguous run of `true` in
/// `thin_mask`. Returns true and writes `*out` only when:
///   - exactly one such run exists, AND
///   - the run is strictly interior (lo > 0, hi < N - 1), AND
///   - the endpoints (`thin_mask.front()`, `thin_mask.back()`) are false.
/// Any other configuration (zero runs, multiple disjoint runs, run
/// touching either endpoint) returns false so the caller falls back to
/// the untrimmed Clipper2 path.
bool extractSingleInteriorRun(const std::vector<bool>& thin_mask,
                              ThinRun* out);

/// Concatenate `base_pts[0..run.lo-1] + base_pts[run.hi+1..N-1]`.
/// The implicit segment between the last preserved leading vertex and
/// the first preserved trailing vertex is the bridge chord across the
/// cusp tip. Returns empty on contract violation
/// (run.lo <= 0 || run.hi >= N-1 || run.lo > run.hi).
std::vector<SPoint2> buildTrimmedOpenPolyline(
    const std::vector<SPoint2>& base_pts, const ThinRun& run);

/// Map `OffsetVertexSource::base_seg` from the trimmed-input indexing
/// (as returned by `offsetWithClipper2` over the trimmed polyline) to
/// original-base indexing. Bridge segment (trimmed index `run.lo - 1`)
/// becomes `base_seg = -1` so Stage C reverse-match treats those
/// offset vertices as Clipper2 join points (forward-fill assigns them
/// to a neighbouring base index). Already-unattributed (-1) sources
/// pass through unchanged. Mutates `polygons` in place.
void remapBaseSegToOriginal(std::vector<OffsetPolygon>& polygons,
                            const ThinRun& run);

/// Pure-geometry Clipper2 offset wrapper.
///
/// @param base            Input polyline in the yz plane.
///                        For closed inputs, the caller may omit the
///                        trailing duplicate vertex; if it is present
///                        the wrapper drops it defensively.
/// @param base_is_closed  true  → EndType::Polygon (implicit closing
///                                 edge from back to front; output is
///                                 a closed offset polygon).
///                        false → EndType::Butt (open-ended; output is
///                                 a one-sided OPEN polyline filtered
///                                 from the Butt-wrap by `side`).
/// @param side            +1 = left  of base (sign(t × d) > 0,
///                              CCW outward for a closed CCW input)
///                        -1 = right of base (sign(t × d) < 0,
///                              CCW inward  for a closed CCW input)
///                        Honored for BOTH closed and open inputs.
///                        For open inputs, the Butt wrap is filtered
///                        post-Clipper2 so each output is a one-sided
///                        open polyline (`is_closed = false`).
/// @param dist            Magnitude of offset distance, > 0.
///
/// Returns zero or more `OffsetPolygon` instances:
///   - closed input → one polygon per Clipper2 path (`is_closed=true`)
///   - open input   → one OPEN polyline per filtered side-run
///                    (`is_closed=false`). Well-formed inputs produce
///                    exactly one run with N or N+1 points (one per
///                    base vertex plus one Butt-cap point at each end).
/// Empty result indicates Clipper2 ate the input completely (local
/// half-thickness < dist) or all wrap vertices landed on the opposite
/// side from the requested one.
///
/// Implementation choices (locked in by A0 evidence; see
/// local/issue-20260515-clipper2-airfoil-a0.md):
///   - JoinType::Miter, miter_limit = 2.0 (defaults below)
///   - precision = 8 (the Clipper2 1.4.0 hard ceiling)
///
/// `join` + `miter_limit` are tunable for the standalone
/// experimentation harness (test/integration/t0_offset_clipper2/);
/// production callers omit them and get the locked-in Miter + 2.0
/// pair unchanged.
enum class JoinTypeChoice {
  Miter,    // sharp corner extended outward until miter_limit, else bevelled
  Square,   // 90° squared corner (square cap-like)
  Bevel,    // flat chord connecting offset edges (shortest)
  Round,    // arc with `arc_tolerance` deviation budget
};

/// @param resample_open   Open-input only. When `true` (default,
///                        production behaviour), `extractOpenRuns`
///                        resamples the raw side-filtered run polyline
///                        at every base vertex via foot-of-perpendicular
///                        projection so downstream sees a 1:1
///                        base ↔ offset alignment over the covered
///                        subset. When `false` (control group used by
///                        `test/integration/t0_offset_clipper2/`), the
///                        resample step is skipped and `points` is the
///                        raw side-filtered Clipper2 run (M can be
///                        ≪ N). Closed inputs ignore this flag (they
///                        never go through resample).
/// @param experimental_open_miter_resample
///                        Open-input only, and only when `join` is
///                        Miter. When true, the resample step rebuilds
///                        a per-base-vertex miter polyline directly
///                        from neighbouring offset lines. This is an
///                        opt-in t0 harness experiment; production
///                        callers keep the default `false`.
std::vector<OffsetPolygon> offsetWithClipper2(
    const std::vector<SPoint2>& base,
    bool                        base_is_closed,
    int                         side,
    double                      dist,
    JoinTypeChoice              join          = JoinTypeChoice::Miter,
    double                      miter_limit   = 2.0,
    bool                        resample_open = true,
    bool                        experimental_open_miter_resample = false);

/// Resample one open offset run to base-vertex resolution (foot-of-
/// perpendicular, one point per covered base vertex → forces M=N over the
/// covered subset). No-op unless `runs` holds exactly one open run with >= 2
/// points; mutates `runs[0]` in place. `do_miter_resample` selects the
/// experimental clean-miter variant. Extracted from `extractOpenRuns` so the
/// offset / build-base-offset-map split can invoke resample from the map step
/// (plan: offset = raw geometry, build-base-offset-map = staircase + resample).
void resampleOpenRuns(std::vector<OffsetPolygon>& runs,
                      const std::vector<SPoint2>& base,
                      int side, double dist,
                      bool do_miter_resample = false);

}  // namespace geo
}  // namespace prevabs


// Forward declaration so callers and tests that do not need the full
// PDCEL header chain can still include this header.
class PDCELVertex;

namespace prevabs {
namespace geo {

/// PDCELVertex-aware reverse-match result. Stage D wires this into
/// the legacy `offset()` signature in src/geo/offset.cpp.
struct ReverseMatchResult {
  /// Newly allocated PDCELVertex* (caller takes ownership).
  /// Convention:
  ///   - closed input  → `offset_vertices.front() == .back()` (same
  ///                     pointer), matching the PreVABS Baseline
  ///                     trailing-duplicate convention. Size =
  ///                     M_off_raw + 1.
  ///   - open   input  → `offset_vertices.front()` and `.back()` are
  ///                     distinct pointers, end-to-end 1:1 aligned
  ///                     with `base.front()` and `base.back()`.
  ///                     Size = M_off_raw.
  std::vector<PDCELVertex*> offset_vertices;
  /// Per-vertex origin tag, parallel to `offset_vertices`. See
  /// `OffsetPolygon::resampled` for the convention. For closed inputs
  /// the trailing-duplicate slot copies the flag of the first vertex.
  std::vector<bool>         offset_resampled;
  /// Debug-only pre-resample raw Clipper2 vertex snapshot — see
  /// `ReverseMatchPlan::pre_resample_raw_points`. Empty when the
  /// open-path resample step never triggered.
  std::vector<SPoint2>      pre_resample_raw_points;
  /// Staircase per geo_types.hpp:27.
  ///   - closed → last entry is `(N_distinct, M_off_raw)` wrap pair.
  ///   - open   → last entry is `(N_distinct - 1, M_off_raw - 1)`,
  ///              no wrap pair.
  BaseOffsetMap             id_pairs;
  std::vector<int>          dropped_base_ranges_lo;
  std::vector<int>          dropped_base_ranges_hi;
  bool                      ok = false;
};

/// Stage C adapter (per plan-20260514 §5). Thin wrapper around
/// `planReverseMatch` that:
///   - extracts SPoint2 from PDCELVertex* (dropping the trailing
///     duplicate vertex if the caller passes a closed Baseline with
///     `base.front() == base.back()`; for open inputs the input
///     vector is consumed unchanged).
///   - calls `planReverseMatch`,
///   - allocates new PDCELVertex objects for each offset point.
///     For closed inputs, also appends the trailing-duplicate pointer
///     so `offset_vertices.front() == .back()`. Open inputs return
///     end-to-end distinct pointers with size == plan.offset_points
///     size.
///
/// Per plan-20260515 §8.4 this adapter is the planned deletion site
/// when the end-state nested-offset orchestrator replaces
/// `BaseOffsetMap`.
ReverseMatchResult buildBaseOffsetMapFromOffsetPolygons(
    const std::vector<PDCELVertex*>&   base,
    bool                               base_is_closed,
    int                                side,
    double                             dist,
    const std::vector<OffsetPolygon>&  polygons);

}  // namespace geo
}  // namespace prevabs
